version: '0.1'

services:
  react-frontend:
    container_name: tces-prod-frontend
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    volumes:
      - ./client:/home/node/app
    working_dir: /home/node/app
    ports:
      - '80:80'
      - '443:443'
    depends_on: 
      - nodejs-middleware

  nodejs-middleware:
    container_name: tces-prod-backend   
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'